#!/bin/bash
# Install dependencies
sudo curl git apt-get install vim clang-format
# Copy vimrc
cp vimrc ~/.vimrc
mkdir ~/.vim
cp clang-format.py ~/.vim/
# Clone pathogen
mkdir ~/.vim/autoload -p
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
# Install color
mkdir ~/.vim/colors
cd ~/.vim/colors
git clone https://github.com/morhetz/gruvbox
cp gruvbox/colors/* .
# Install plugins
mkdir ~/.vim/bundle
cd ~/.vim/bundle
git clone https://github.com/msanders/snipmate.vim.git
cd snipmate.vim
# Remove default snippets, it will clone custom ones
rm -r snippets
cd ..
git clone https://github.com/kien/ctrlp.vim.git
git clone https://github.com/scrooloose/nerdtree
git clone https://github.com/vim-airline/vim-airline
git clone https://github.com/Alberto-Izquierdo/vim-snippets
git clone https://github.com/rust-lang/rust.vim.git
if ! grep -q 'stty -ixon' .bashrc
then
    echo 'stty -ixon' >> ~/.bashrc
fi
