#!/bin/bash
pwd=$(pwd)
# Install dependencies
sudo apt-get install curl git vim clang-format silversearcher-ag
mkdir ~/.vim
# Copy vimrc
cp vimrc ~/.vimrc
cp clang-format.py ~/.vim/
# Clone pathogen
cd ~/.vim
git clone https://github.com/tpope/vim-pathogen.git
cp -r vim-pathogen/autoload ~/.vim
sudo rm -r vim-pathogen
# Install color
mkdir ~/.vim/colors
cd ~/.vim/colors
git clone https://github.com/morhetz/gruvbox
cp gruvbox/colors/* .
# Install plugins
mkdir ~/.vim/bundle
cd ~/.vim/bundle
git clone https://github.com/msanders/snipmate.vim.git
cd snipmate.vim
# Remove default snippets, it will clone custom ones
rm -r snippets
cd ..
git clone https://github.com/kien/ctrlp.vim.git
git clone https://github.com/scrooloose/nerdtree
git clone https://github.com/vim-airline/vim-airline
git clone https://github.com/Alberto-Izquierdo/vim-snippets
git clone https://github.com/rust-lang/rust.vim.git
git clone https://github.com/rust-lang/rust.vim.git
git clone https://github.com/fatih/vim-go.git
git clone https://github.com/tpope/vim-fugitive.git
if ! grep -q 'stty -ixon' ~/.bashrc
then
    echo 'stty -ixon' >> ~/.bashrc
fi
cd $(pwd)
